// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CnSharp.VisualStudio.NuPack
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidNuPackPackageString = "b90fffa4-9f8a-4bbf-9a4f-16880fbfea9c";
        public static Guid guidNuPackPackage = new Guid(guidNuPackPackageString);

        public const string guidDeployPackageCmdSetString = "7d371e13-afd3-4d17-8c84-9bf0fe65da2a";
        public static Guid guidDeployPackageCmdSet = new Guid(guidDeployPackageCmdSetString);

        public const string guidPackageDeploymentImageString = "04e5e168-97c3-438a-b67e-35b4b90e81e3";
        public static Guid guidPackageDeploymentImage = new Guid(guidPackageDeploymentImageString);

        public const string guidMigrateNuspecToProjectCmdSetString = "df6aceb6-5353-4ec9-9174-069d2b2605ce";
        public static Guid guidMigrateNuspecToProjectCmdSet = new Guid(guidMigrateNuspecToProjectCmdSetString);

        public const string guidPackagePropertyImageString = "a266cd18-7edb-45c4-adb6-279ebf281d84";
        public static Guid guidPackagePropertyImage = new Guid(guidPackagePropertyImageString);

        public const string guidMigrateNuspecToProjectUIRuleString = "c0d08b33-dc49-4362-9b60-cc7761e29944";
        public static Guid guidMigrateNuspecToProjectUIRule = new Guid(guidMigrateNuspecToProjectUIRuleString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int DeployMenuGroup = 0x1020;
        public const int cmdidDeployPackageCommand = 0x0100;
        public const int deployPic = 0x0001;
        public const int MigrateNuspecMenuGroup = 0x1020;
        public const int cmdidMigrateNuspecToProjectCommand = 0x0101;
        public const int migrateNuspecPic = 0x0001;
    }
}